# Generated by Django 4.1.4 on 2022-12-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcomment',
            name='author',
        ),
    ]
